baseURL = 'https://epe105.github.io/'
languageCode = 'en-us'
title = 'Techie Adventures of Manny Evangelista'
theme = "m10c"

[params]
  author = "Manny Evangelista
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/epe105"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/Manny_PSU"