baseURL = 'https://epe105.github.io/'
languageCode = 'en-us'
title = "Manny Evangelista"
theme = "m10c"


[params]
  author = "Manny Evangelista"
  description = "Never stop learning! Documenting my adventures in technology."

[params.style]
  darkestColor = "#2e6cb8"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"

  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/manny-evangelista/"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/epe105"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/Manny_PSU"

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3